---
port: 9888 
plugins:
  - sandcat
  - stockpile
  - compass
  - terminal
users:
  red:
    admin: admin
  blue:
    blue: admin
api_key: ADMIN123
exfil_dir: /tmp
reports_dir: /tmp
crypt_salt: REPLACE_WITH_RANDOM_VALUE
app.redirect.http: http://0.0.0.0:9888
