---
port: 8888
plugins:
  - sandcat
  - stockpile
  - compass
  - terminal
users:
  red:
    admin: admin
  blue:
    blue: admin
api_key: ADMIN123
exfil_dir: /tmp
reports_dir: /tmp
crypt_salt: REPLACE_WITH_RANDOM_VALUE
app.contact.http: http://0.0.0.0:8888
app.contact.tcp: 0.0.0.0:5678
app.contact.udp: 0.0.0.0:5679