---
port: 8888
plugins:
  - sandcat
  - compass
  - terminal
  - stockpile
  - pluginA
  - pluginB
users:
  red:
    admin: admin
  blue:
    blue: admin
api_key: ADMIN123
exfil_dir: /tmp
reports_dir: /tmp
crypt_salt: REPLACE_WITH_RANDOM_VALUE
app.redirect.http: http://0.0.0.0:8888