---

host: 0.0.0.0
port: 8888
exfil_dir: /tmp
untrusted_timer: 60
plugins:
  - sandcat
  - stockpile
  - compass
debug: True
api_key: ADMIN123
users:
  admin: admin
file_encryption: True
crypt_salt: REPLACE_WITH_RANDOM_VALUE
