---
port: 8888
plugins:
  - sandcat
  - stockpile
  - compass
  - terminal
users:
  admin: admin
api_key: ADMIN123
exfil_dir: /tmp
reports_dir: /tmp
crypt_salt: REPLACE_WITH_RANDOM_VALUE
facts:
  - trait: app.http
    value: http://0.0.0.0:8888
  - trait: app.tcp
    value: 0.0.0.0:5678
  - trait: app.udp
    value: 0.0.0.0:5679