# General Configuration
ability_refresh: 60
crypt_salt: REPLACE_WITH_RANDOM_VALUE
encryption_key: ADMIN123
host: 0.0.0.0
port: 8888
exfil_dir: /tmp/caldera
reports_dir: /tmp
objects:
  planners:
    default: atomic

# User Authentication
users:
  blue:
    blue: admin
  red:
    admin: admin
    red: admin

# Auth Module
auth:
  login:
    handler:
      module: default

# Reachable Host Traits
reachable_host_traits:
  - remote.host.fqdn
  - remote.host.ip

# Application Contacts
app:
  contact:
    dns:
      domain: mycaldera.caldera
      socket: 0.0.0.0:8853
    gist: API_KEY
    html: /weather
    http: http://0.0.0.0:8888
    tcp: 0.0.0.0:7010
    udp: 0.0.0.0:7011
    websocket: 0.0.0.0:7012
    slack:
      api_key: SLACK_TOKEN
      bot_id: SLACK_BOT_ID
      channel_id: SLACK_CHANNEL_ID
    ftp:
      host: 0.0.0.0
      port: 2222
      user: caldera_user
      pword: caldera
      server:
        dir: ftp_dir
    tunnel:
      ssh:
        socket: 0.0.0.0:8022
        host_key_file: REPLACE_WITH_KEY_FILE_PATH
        host_key_passphrase: REPLACE_WITH_KEY_FILE_PASSPHRASE
        user_name: sandcat
        user_password: s4ndc4t!

# Plugin Configuration
plugins:
  - access
  - atomic
  - compass
  - debrief
  - fieldmanual
  - manx
  - response
  - sandcat
  - stockpile
  - training

# Requirements
requirements:
  go:
    type: installed_program
    command: go version
    version: 1.19
  python:
    type: python_module
    module: sys
    attr: version
    version: 3.9.0
