api_key_blue: BLUEADMIN123
api_key_red: ADMIN123
app.contact.gist: API_KEY
app.contact.html: /weather
app.contact.http: http://0.0.0.0:8888
app.contact.tcp: 0.0.0.0:7010
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012
crypt_salt: REPLACE_WITH_RANDOM_VALUE
encryption_key: ADMIN123
exfil_dir: /tmp
plugins:
- sandcat
- stockpile
- compass
- manx
- response
- gameboard
- training
- access
port: 8888
reports_dir: /tmp
users:
  blue:
    blue: admin
  red:
    admin: admin
    red: admin
