---

host: 127.0.0.1
port: 8888
sockets:
  - 8880
planner: plugins.stockpile.app.sequential
stores:
  - plugins/stockpile/payloads
  - plugins/adversary/payloads
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
users:
  admin: admin

