---

host: 127.0.0.1
port: 8888
planner: plugins.stockpile.app.sequential
payloads:
  - plugins/stockpile/payloads
exfil_dir: /tmp
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
users:
  admin: admin
