---

host: 127.0.0.1
port: 8888
sockets:
  - 8880
planner: plugins.stockpile.app.sequential
proxy: haproxy
stores:
  - payloads
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
users:
  admin: admin

