---

host: 127.0.0.1
port: 8888
planner: plugins.stockpile.app.sequential
stores:
  - plugins/stockpile/payloads
  - plugins/adversary/payloads
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
  - ssl
users:
  admin: admin
