---

host: 127.0.0.1
port: 8888
planner: plugins.stockpile.app.sequential
proxy: haproxy
stores:
  - payloads
xorkey: 9Nkx8EKZuo6guQi4PKrmO1KoxHePcQ4z5EKuHqSLYEaVzV00My0DYPHREJo73gzzUtCrP9QYiul9WTrYwqQBbs2hU5Hmxilgu5wn
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
users:
  admin: admin
