---

host: 127.0.0.1
port: 8888
sockets:
  - 8880
terminal:
  host: 127.0.0.1
  port: 8880
debug_level: ERROR
planner: plugins.stockpile.app.sequential
stores:
  - plugins/stockpile/filestore
  - plugins/adversary/filestore
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
users:
  admin: admin

