name: Greetings

on: [pull_request, issues]

permissions:
  contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@bd33205aa5c96838e10fd65df0d01efd613677c1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Looks like your first issue -- we aim to respond to issues as quickly as possible. In the meantime, check out our documentation here: http://caldera.readthedocs.io/'
        pr-message: 'Wohoo! Your first PR -- thanks for contributing!'
